// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUZo5JzxqeKaHRs4LJ-amxZEKQ3w2kfcs',
    appId: '1:379381007222:web:1e75e0300aeb605a8bf057',
    messagingSenderId: '379381007222',
    projectId: 'studybuddy-5a0f6',
    authDomain: 'studybuddy-5a0f6.firebaseapp.com',
    storageBucket: 'studybuddy-5a0f6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvbrSP0h7K3JV8S-VIjIzZUDwggxxdMa4',
    appId: '1:379381007222:android:a8d5d39768ec0c3d8bf057',
    messagingSenderId: '379381007222',
    projectId: 'studybuddy-5a0f6',
    storageBucket: 'studybuddy-5a0f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1VSyaoDKKxRmMj7ui1saCZL0H3u5v4Eg',
    appId: '1:379381007222:ios:a2e8c25a3982bf638bf057',
    messagingSenderId: '379381007222',
    projectId: 'studybuddy-5a0f6',
    storageBucket: 'studybuddy-5a0f6.firebasestorage.app',
    iosBundleId: 'com.example.studybuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1VSyaoDKKxRmMj7ui1saCZL0H3u5v4Eg',
    appId: '1:379381007222:ios:a2e8c25a3982bf638bf057',
    messagingSenderId: '379381007222',
    projectId: 'studybuddy-5a0f6',
    storageBucket: 'studybuddy-5a0f6.firebasestorage.app',
    iosBundleId: 'com.example.studybuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUZo5JzxqeKaHRs4LJ-amxZEKQ3w2kfcs',
    appId: '1:379381007222:web:07eacf274d515f058bf057',
    messagingSenderId: '379381007222',
    projectId: 'studybuddy-5a0f6',
    authDomain: 'studybuddy-5a0f6.firebaseapp.com',
    storageBucket: 'studybuddy-5a0f6.firebasestorage.app',
  );
}
